name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'zulu'
      - name: Install Linux dependencies
        run: sudo apt-get install libplist-dev libimobiledevice-dev libirecovery-1.0-dev
        if: runner.os == 'Linux'
      - name: Gradle build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --no-daemon
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: build/distributions/*
      - name: Upload reports on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failure-${{ runner.os }}
          path: build/reports/
  release:
    name: Create pubilc releases
    runs-on: ubuntu-latest
    needs: build
    if: "startsWith(github.event.head_commit.message, 'Release')"
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
      - name: Get version from commit
        run: echo "VERSION=$(echo ${{ github.event.commits[0].message }} | awk '{print $2}')" >> $GITHUB_ENV
      - name: Release public builds
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.VERSION }}"
          prerelease: false
          draft: true
          files: "**"
